/**
 * In-memory TODO manager MCP server (TypeScript).
 *
 * Generated by mcpforge as an example TypeScript server.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

const server = new McpServer({ name: "Todo Manager TS", version: "0.1.0" });

interface Todo {
	id: string;
	title: string;
	description: string;
	completed: boolean;
	created_at: string;
}

const todos = new Map<string, Todo>();
let nextId = 1;

server.tool(
	"create_todo",
	"Create a new TODO item with a title and optional description.",
	{
		title: z.string().describe("The title of the TODO item"),
		description: z
			.string()
			.optional()
			.default("")
			.describe("Optional longer description"),
	},
	async ({ title, description }) => {
		if (!title.trim()) {
			throw new Error("title must not be empty");
		}
		const id = String(nextId++);
		const todo: Todo = {
			id,
			title: title.trim(),
			description: description ?? "",
			completed: false,
			created_at: new Date().toISOString(),
		};
		todos.set(id, todo);
		return {
			content: [{ type: "text" as const, text: JSON.stringify(todo) }],
		};
	},
);

server.tool(
	"list_todos",
	"List all TODO items, optionally filtered by completion status.",
	{
		completed: z
			.boolean()
			.optional()
			.describe("Filter by completion status, or omit for all"),
	},
	async ({ completed }) => {
		let result = Array.from(todos.values());
		if (completed !== undefined) {
			result = result.filter((t) => t.completed === completed);
		}
		return {
			content: [{ type: "text" as const, text: JSON.stringify(result) }],
		};
	},
);

server.tool(
	"get_todo",
	"Retrieve a single TODO item by its ID.",
	{ todo_id: z.string().describe("The unique ID of the TODO item") },
	async ({ todo_id }) => {
		const todo = todos.get(todo_id);
		if (!todo) {
			throw new Error(`todo_id '${todo_id}' not found`);
		}
		return {
			content: [{ type: "text" as const, text: JSON.stringify(todo) }],
		};
	},
);

server.tool(
	"update_todo",
	"Update an existing TODO item by ID.",
	{
		todo_id: z.string().describe("The unique ID of the TODO item"),
		title: z
			.string()
			.optional()
			.describe("New title, or omit to keep existing"),
		completed: z
			.boolean()
			.optional()
			.describe("New completion status, or omit to keep existing"),
	},
	async ({ todo_id, title, completed }) => {
		const todo = todos.get(todo_id);
		if (!todo) {
			throw new Error(`todo_id '${todo_id}' not found`);
		}
		if (title !== undefined) {
			todo.title = title.trim();
		}
		if (completed !== undefined) {
			todo.completed = completed;
		}
		return {
			content: [{ type: "text" as const, text: JSON.stringify(todo) }],
		};
	},
);

server.tool(
	"delete_todo",
	"Delete a TODO item by ID.",
	{ todo_id: z.string().describe("The unique ID of the TODO item to delete") },
	async ({ todo_id }) => {
		if (!todos.has(todo_id)) {
			throw new Error(`todo_id '${todo_id}' not found`);
		}
		todos.delete(todo_id);
		return {
			content: [
				{
					type: "text" as const,
					text: JSON.stringify({ deleted: true, id: todo_id }),
				},
			],
		};
	},
);

const transport = new StdioServerTransport();
await server.connect(transport);
